[package]
name = "rust_demo_2"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "loxim"
path = "src/main.rs"

[profile.release]
opt-level = 2

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
